### ISSUE TITLE
The CSV and JSON inputs should be either a part of the interface or a part of the package

### ISSUE THREAD

**Issue by hosaka** [dextor19/downtable#4]
To use Json, the `MarkdownTable.AddJSONFileTable` is used, to use CSV as input the `downtable.WithCSVFile` is available. These are 2 different ways to arrive at the same point: constructing a markdown table. They should either live in the interface, or outside of it and probably have a consistent name, "FromJson", "WithJson" or similar.

**Comment by dextor19** [comment]
I personally like the direct struct method approach `MarkdownTable.AddJSONFileTable` since this seems more intuitive to me, however I saw a lot of examples from other go projects using the `downtable.WithCSVFile`. I guess I will just stick with my preference which is the single struct method rather than having a function providing a output for a struct method `MarkdownTable.AddTable`.

I will reimplement the `downtable.WithCSVFile` to be `MarkdownTable.AddTableFromCSVFile()` a method directly on the `table` struct.

Also should I rename the `MarkdownTable.AddJSONFileTable` to `MarkdownTable.AddTableFromJSONFile()` ?
